# Generated by Django 3.2 on 2021-05-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egygold', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-post_date',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
