# Generated by Django 3.2 on 2021-05-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egygold', '0005_alter_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان التعليق'),
        ),
    ]
